id: I41291361
legacy_id: P007065
ocr_import_info:
  bdrc_scan_id: W20865
  source: bdrc
  ocr_info:
    timestamp: '2021-01-22T07:13:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:42:17.905821+00:00'
last_modified: 2022-09-01 21:43:23.212483
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W20865
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20865
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ནམ་མཁའ་འཇིགས་མེད།
  author: ལྷ་བཙུན་ནམ་མཁའ་འཇིགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.7603714997515396
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I0174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0174
      total_pages: 646
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0174.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7811294641875732
    legacy_id: v001
  I0177:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0177
      total_pages: 555
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0177.txt
    statistics:
      ocr_word_median_confidence_index: 0.77
      ocr_word_mean_confidence_index: 0.7142997194585397
    legacy_id: v004
  I0175:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0175
      total_pages: 559
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0175.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7888899765386737
    legacy_id: v002
  I0176:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0176
      total_pages: 731
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0176.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8345997390120826
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
