id: I41291361
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:10:22+00:00'
last_modified: '2022-06-09T04:29:03.454384+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20865
  title: གསུང་འབུམ། ནམ་མཁའ་འཇིགས་མེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1686':
      image_group_id: I0174
      title: ''
      total_pages: 646
      order: 1
      base_file: 1686.txt
    FDD2:
      image_group_id: I0175
      title: ''
      total_pages: 559
      order: 2
      base_file: FDD2.txt
    566A:
      image_group_id: I0176
      title: ''
      total_pages: 731
      order: 3
      base_file: 566A.txt
    1A86:
      image_group_id: I0177
      title: ''
      total_pages: 555
      order: 4
      base_file: 1A86.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
